export default {
    STARTUP: 'STARTUP',
    SET_APP_PROPS: 'SET_APP_PROPS',
    TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',

    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOG_IN: 'LOG_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',

    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    PUT_PROFILES: 'PUT_PROFILES',
    PUT_PROFILES_SUCCESS: 'PUT_PROFILES_SUCCESS',
    PUT_PROFILES_FAILURE: 'PUT_PROFILES_FAILURE',

    GET_SETTINGS : 'GET_SETTINGS',
    GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE',

    GET_QUESTIONS: 'GET_QUESTIONS',
    GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
    GET_QUESTIONS_FAILURE: 'GET_QUESTIONS_FAILURE',

    POST_REQUEST: 'POST_REQUEST',
    POST_REQUEST_SUCCESS: 'POST_REQUEST_SUCCESS',
    POST_REQUEST_FAILURE: 'POST_REQUEST_FAILURE'

}