export default {
    STARTUP: 'STARTUP',
    SET_APP_PROPS: 'SET_APP_PROPS',
    TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',

    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOG_IN: 'LOG_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',

    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    POST_PROFILES: 'POST_PROFILES',
    POST_PROFILES_SUCCESS: 'POST_PROFILES_SUCCESS',
    POST_PROFILES_FAILURE: 'POST_PROFILES_FAILURE',

    GET_SETTINGS : 'GET_SETTINGS',
    GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE'

    // GET_SERVICES: 'GET_SERVICES',
    // GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
    // GET_SERVICES_FAILURE: 'GET_SERVICES_FAILURE',
    //
    // GET_LANGUAGES: 'GET_LANGUAGES',
    // GET_LANGUAGES_SUCCESS: 'GET_LANGUAGES_SUCCESS',
    // GET_LANGUAGES_FAILURE: 'GET_LANGUAGES_FAILURE'

}